# This is a basic workflow to help you get started with Actions

name: Deploy Server

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Vultr Region id, see: https://api.vultr.com/v2/regions'
        required: true
        default: 'syd'
      plan:
        description: 'Vultr Plan id, see: https://api.vultr.com/v2/plans'
        required: true
        default: 'vc2-1c-1gb'
      label:
        description: 'Server label'
        required: false
        default: 'GitHub deployed'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: |
          curl --location --request POST 'https://api.vultr.com/v2/instances' \
          --header 'Authorization: Bearer '${VULTR_API_KEY} \
          --header 'Content-Type: application/json' \
          --data-raw '{
          	"region" : "${{ github.event.inputs.region }}",
          	"plan" : "${{ github.event.inputs.plan }}",
            "label" : "${{ github.event.inputs.label }}",
            "snapshot_id" : "'`curl \
          	            --silent \
                       --location \
                       --request GET 'https://api.vultr.com/v2/snapshots' \
                       --header 'Authorization: Bearer '${VULTR_API_KEY} \
                       | jq --raw-output .snapshots[0].id`'",
            "user_data" : "dGVzdA==",
            "backups": "enabled"
          }'
