name: Destroy Snapshots
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vultr delete all exisiting snapshots
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        run: |
          curl  \
          --silent \
          --location \
          --request GET 'https://api.vultr.com/v2/snapshots' \
          --header 'Authorization: Bearer '${VULTR_API_KEY} \
          | jq --raw-output .snapshots[].id  \
          | xargs -n 1 -r -P 1 -I{} curl \
          --location \
          --request DELETE 'https://api.vultr.com/v2/snapshots/{}' \
          --header 'Authorization: Bearer '${VULTR_API_KEY}
